# Introduction to Numpy and Matplotlib

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------------- ------------ 41.0/60.8 kB 326.8 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 358.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 1.7 MB/s eta 0:00:08
    --------------------------------------- 0.2/12.6 MB 2.1 MB/s eta 0:00:06
    --------------------------------------- 0.3/12.6 MB 2.8 MB/s eta 0:00:05
    --------------------------------------- 0.3/12.6 MB 2.8 MB/s eta 0:00:05
   - -------------------------------------- 0.5/12.6 MB 2.7 MB/s eta 0:00:05
   - -------------------------------------- 0.6/12.6 MB 2.3 MB/s eta 0:00:06
   -- ------------------------------------- 0.7/12.6 MB 2.1 MB/s eta 0:00:06
   -- --


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

# create a Python list of temperature in degree celcius

In [6]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

# converting this list into one-dimensional Numpy array

In [9]:
c = np.array(cvalues)
print(cvalues)
print(type(cvalues))
print(c)
print(type(c))

[20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
<class 'list'>
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>


# 4.Element-wise Operations in Numpy (Scalar Operations)

In [11]:
F = c * 9/5 + 32
print(F)



[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


In [13]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape) 
B = np.array([[7,8,9],[10,11,12]])
print(B)
print(B.shape)
C = A+B
print(C)
print(C.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8  9]
 [10 11 12]]
(2, 3)
[[ 8 10 12]
 [14 16 18]]
(2, 3)


# 5. Array Indexing

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:,0:2]
print(b)
print(a[0,0])
print(a)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 6. Boolean Array Indexing (for Filtering)

In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
# We can do all of the above in a single concise statement:
print(a[a > 2]) # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# 7. Numpy Simple Math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum
print(x + y)
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
