# Introduction to Numpy and Matplotlib

In [1]:
pip install numpy

In [2]:
import numpy as np

# create a Python list of temperature in degree celcius

In [3]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]

# converting this list into one-dimensional Numpy array

In [4]:
c = np.array(cvalues)
print(cvalues)
print(type(cvalues))
print(c)
print(type(c))

[20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]
<class 'list'>
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]
<class 'numpy.ndarray'>


# 4.Element-wise Operations in Numpy (Scalar Operations)

In [5]:
F = c * 9/5 + 32
print(F)



[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


In [6]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A.shape) 
B = np.array([[7,8,9],[10,11,12]])
print(B)
print(B.shape)
C = A+B
print(C)
print(C.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8  9]
 [10 11 12]]
(2, 3)
[[ 8 10 12]
 [14 16 18]]
(2, 3)


# 5. Array Indexing

In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:,0:2]
print(b)
print(a[0,0])
print(a)

[[ 1  2]
 [ 5  6]
 [ 9 10]]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 6. Boolean Array Indexing (for Filtering)

In [8]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
# We can do all of the above in a single concise statement:
print(a[a > 2]) # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


# 7. Numpy Simple Math

Addition Operation

In [9]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum
print(x + y)
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


Multiplication Operation

In [11]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


Substraion Operation

In [13]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
